dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: token1 # replace this 
        apiUrl: http://proxy-public/hub/api
      type: jupyterhub

jupyterhub:
  hub:
    config:
      Authenticator:
        admin_users:
        - admin
      JupyterHub:
        admin_access: true
        authenticator_class: nativeauthenticator.NativeAuthenticator          
    services:
      dask-gateway:
        apiToken: token1 # replace this

  proxy:
    secretToken: token2 # replace this 
