registry:
  url: 'cerit.io'
  password: '<password>' # replace this
  username: '<username>' # replace this

jupyterhub:
  hub:
    config:
      BinderSpawner:
        auth_enabled: false
      Authenticator:
        admin_users:
        - admin
      JupyterHub:
        admin_access: true
        authenticator_class: nativeauthenticator.NativeAuthenticator          
    services:
      dask-gateway:
        apiToken: token1 # replace this
      binder:
        oauth_client_id: service-binderhub
        oauth_no_confirm: true
        oauth_redirect_uri: "https://daskbinder.vm.fedcloud.eu/oauth_callback"

  proxy:
    secretToken: token2 # replace this 
